default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: kakeibo_development
  host: db
  username: root
  password: rootpassword

test:
  <<: *default
  database: kakeibo_test

production:
  <<: *default
  database: kakeibo_production
